### ISSUE TITLE
How does genswift.sh work?

### ISSUE THREAD

**Issue by danilaplee** [SwiftJava/SwiftJava#6]
I seem to get something like this all the time
```
path/to/my/project# ~/SwiftJava/genswift.sh com.jh ./genie.jar
/root/SwiftJava

0 files written.
```

**Comment by johnno1962** [comment]
If you look in the genie.ja file, the prefix is org/genie so you want to type something like ~/SwiftJava/genswift.sh org.genie ./genie.jar but genie.jar should be a jar containing your classes you want Swift wrappers for and org.genie should be your prefix.

**Comment by danilaplee** [comment]
sorry for my stupidity on this friday evening but here are some other questions that came up:

1) so i should edit the jar file to contain my namespace?
```
...

$JAVA_HOME/bin/javac me/starpy/{*,*/*}.java &&

$JAVA_HOME/bin/jar cfv ../starpy.jar me/starpy/{*,*/*}.class &&

\cp ../starpy.jar ~/.starpy.jar
```
2) then generate the proper jar file in my gradle directory?
3) then i can build app with my namespace <me.starpy> in my gradle project directory like: 
~/SwiftJava/genswift.sh me.starpy ./starpy.jar 
4) the gradle project directory is based on this repo https://github.com/SwiftJava/swift-android-samples/tree/master/swifthello

**Comment by johnno1962** [comment]
For an android project you don’t need a ~/.starpy.jar. Have a look at the script “genhello.sh" which is used for the swifthello example.

**Comment by danilaplee** [comment]
if i edit genhello.sh like this:
```
...
$JAVA_HOME/bin/javac -parameters me/starpy/*.java &&

$JAVA_HOME/bin/jar cf /tmp/hello.jar me/starpy/*.class &&

# The last argument is the frameworks the project
# is dependent on. java_lang for example will add
# about 2mb to the app's apk and needs to be added
# to the project's src/main/swift/Package.swift

cd .. && ./genswift.sh me.starpy /tmp/hello.jar "" &&
```
will this hello.jar be working for my namespace then?
seems to me here it is used and generated beforehand
should i also make a file like this in my project:
https://github.com/SwiftJava/swift-android-samples/blob/master/swifthello/src/main/java/org/genie/com_jh/SwiftHello_ListenerProxy.java
or is it also generated?

**Comment by johnno1962** [comment]
Oh dear. It is all rather complicated isn’t it. You’re on the right track. Any Listener Proxies will be generated from the protocol you privde in  /tmp/hello.jar and needs to be built into your app..

**Comment by danilaplee** [comment]
ok so i've run the following test, i've created a copy of genhello.sh, called gensdk.sh for my project:

```
user@starpy:~/SwiftJava# micro ./gensdk.sh
 1 #!/bin/bash
 2 #
 3 # Generates Proxy and Swift sources for swifthello Android sample
 4 # Note use of -parameters option when compiling to record names
 5 #
 6
 7 #cd `dirname $0`/src &&
 8
 9 \rm `find src/me/starpy/sdk -name '*.class'` 2>/dev/null
10
11 \rm `find me.starpy.sdk -name '*.swift'` 2>/dev/null
12
13 #\rm `find sdk-android/src/main/swift/Sources -name 'StarpySDK*.swift'` 2>/dev/null
14
15 $JAVA_HOME/bin/javac -parameters src/me/starpy/sdk/*.java &&
16
17 $JAVA_HOME/bin/jar cf /tmp/sdk.jar src/me/starpy/sdk/*.class &&
18
19 # The last argument is the frameworks the project
20 # is dependent on. java_lang for example will add
21 # about 2mb to the app's apk and needs to be added
22 # to the project's src/main/swift/Package.swift
23
24 ./genswift.sh me.starpy.sdk /tmp/sdk.jar "" &&
25
26 mkdir -p src/main/java/{me/starpy/sdk,org/genie/me_starpy_sdk} &&
27
28 \cp -v src/me/starpy/sdk*.java src/main/java/me/starpy/sdk &&
29 \cp -v src/org/genie/me_starpy_sdk/*.java src/main/java/org/genie/me_starpy_sdk &&
30
31 \cp -v me_starpy_sdk/Sources/*.swift ./sdk-android/src/main/swift/Sources
32
```

and here is what i got:

```
user@starpy:~/SwiftJava# ./gensdk.sh
/home/user/SwiftJava

0 files written.
'src/me/starpy/sdk/StarpySDK.java' -> 'src/main/java/me/starpy/sdk/StarpySDK.java'
'src/org/genie/me_starpy_sdk/StarpySDK_ListenerProxy.java' -> 'src/main/java/org/genie/me_starpy_sdk/StarpySDK_ListenerProxy.java'
cp: cannot stat 'me_starpy_sdk/Sources/StarpySDK*.swift': No such file or directory

```


here is my main.swift file:

```

import java_swift
import Foundation

let stSDK = StarpySDK()

var responder: StarpySDK_ResponderForward!

class ListenerImpl: StarpySDK_ListenerBase {

    typealias CompletionHandler = (_ status: StarpySDKStatus) -> Void

	override func RequestLogin(phone:String) {
        stSDK.RequestLogin(phone, done:{ response in
        	responder.RequestedLogin(response)
        })
    }

    override func ConfirmLogin(code:String) {
        stSDK.ConfirmLogin(code, done: { response in
        	responder.ConfirmedLogin(response)
        })
    }
}	

@_silgen_name("Java_me_starpy_sdk_StarpySDK_bind")
public func bind( __env: UnsafeMutablePointer<JNIEnv?>, __this: jobject?, __self: jobject? )-> jobject? {
    responder = StarpySDK_ResponderForward( javaObject: __self )
    return ListenerImpl().javaObject
}


```

my StarpySDK.swift:
```
import Foundation;
import Dispatch;

class StarpySDK {
	
    let queue = DispatchQueue.global()

	public typealias CompletionHandler = (_ status: String) -> Void

	public func RequestLogin(phone:String, done:@escaping CompletionHandler) {
        queue.async() {
			...
			done("success")
		}

	}

	public func ConfirmLogin(code:String, done:@escaping CompletionHandler) {
        queue.async() {
			...
			done("success")
		}
	}
}


```


and my StarpySDK.java file:


```

package me.starpy.sdk;

import android.app.Activity;
import android.os.Handler;
import android.os.Bundle;
import android.widget.TextView;

import me.starpy.sdk.StarpySDK.Listener;
import me.starpy.sdk.StarpySDK.Responder;

class StarpySDK extends Activity implements Responder {

    static Listener listener;
    Handler mainHandler;

    private static void loadNativeDependencies() {
        // Load libraries
        System.loadLibrary("StarpySDK");
    }

    /** Called when the activity is first created. */
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        mainHandler = new Handler(StarpyApp.getContext().getMainLooper());
        setContentView(R.layout.main);
        loadNativeDependencies();
        listener = bind( this );
    }
    // @Override
    public void requestedLogin(String result) {
        // return status;
    }
    // @Override
    public void confirmedLogin(String result) {
        // return status;
    }



    native Listener bind( Responder self );
}



```

and my StarpySDK_ListenerProxy.java file:

```

package org.genie.me_starpy_sdk;

public class StarpySDK_ListenerProxy implements me.starpy.sdk.StarpySDK.Listener {

    long swiftObject;

    StarpySDK_ListenerProxy( long swiftObject ) {
        this.swiftObject = swiftObject;
    }


    public native void __RequestLogin( java.lang.String phone );

    public void RequestLogin( java.lang.String phone)  {
        __RequestLogin(phone)
    }


    public native void __ConfirmLogin( java.lang.String code );

    public void ConfirmLogin( java.lang.String code)  {
        __ConfirmLogin(code)
    }
}

```

**Comment by johnno1962** [comment]
This is probably bext resolved with a bit of TeamViewer. Do you have it installed? If you want to connect send your details to swiftjava at johnholdsworth.com

**Comment by danilaplee** [comment]
ok here i uploaded my repo for the app 
https://github.com/danilaplee/StarpySDK

**Comment by danilaplee** [comment]
successfully compiled the android project, thank you.
if anybody get this issue again please see my repo, and gensdk.sh

**Comment by LOG-TAG** [comment]
@danilaplee it will work in OpenJDK or Oracle JDK is mandatory?

**Comment by danilaplee** [comment]
@LOG-TAG i've used OpenJDK

**Comment by LOG-TAG** [comment]
@danilaplee  have you ever faced this kind of error! (tested with openjdk11, adoptopenjdk-8.jdk same error continues ! any basic thing I'm missing? jar file path is 100% right! package is also correct! where I'm missing? (I cloned the repo, directly run the command in SwiftJava-master folder)

```
./genswift.sh com.somename workspace/faspmanager-3.7.2.0.jar
java.lang.ClassNotFoundException: com.somename.
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at genswift.generate(genswift.java:401)
	at genswift.main(genswift.java:302)
```
